### ISSUE TITLE
Release URL required but optional in docs

### ISSUE THREAD

**Issue by kunalnagar** [csexton/release-action#10]
Hey there,

Thanks for providing this action with the `pattern` feature, it's an absolute life-saver!

I ran the following action: https://github.com/kunalnagar/encrypt0r/actions/runs/126946823

Notice how it says that the `required-url` is needed? In the README documentation for this action, it says that it's `optional`.

Maybe I'm missing something? Cheers!

**Comment by 1-alex98** [comment]
``` 
If this release is triggered on a "release" event, the url can automatically be detected. However, if it is chained the release-url will need to be passed in from the previous steps.
```
