### ISSUE TITLE
How does the action know which release to add the files to

### ISSUE THREAD

**Issue by 1-alex98** [csexton/release-action#3]
Can I supply a url of the release? I am creating a release with an action, I would like this action to target this specific release.

**Comment by 1-alex98** [comment]
Ok this is meant to be triggered by a draft right?

**Comment by 1-alex98** [comment]
https://github.com/csexton/release-asset-action/blob/6a964e8a644f28832c3f9a46abc69dda52fc6d17/main.js#L48
How about this?
```
  let url;
  if (! context.payload.release) {
    url = core.getInput('release-url', {required: true});
  }else{
    url= core.getInput('release-url', {required: false}) || context.payload.release.html_url;
  }

  core.setOutput('url', url );
```

**Comment by 1-alex98** [comment]
Like this it could be used for uploading files to autogenerated releases in one go as well.

**Comment by 1-alex98** [comment]
So I thought lets to with your readme and upload files on draft releases, but it seems draft releases do not trigger the github action:

![grafik](https://user-images.githubusercontent.com/19996713/72534240-c6279280-3876-11ea-8713-cce08edd0373.png)

**Comment by csexton** [comment]
Originally I wanted this to work on drafts, but turns out that creating a release draft doesn't create the tag in git. Without a tag I was unable to upload to the release resource. 

I may have been missing something but it was a blocker at the time.

My current use for this action involves creating a draft with another workflow, having a human review and uncheck draft. That'll trigger this and upload any files.

**Comment by 1-alex98** [comment]
Well maybe U can update the read me with a statement similar to this one.

**Comment by 1-alex98** [comment]
And maybe have a look at my workflow maybe that suits you better ;)

**Comment by csexton** [comment]
The problem is it won’t work on a draft. GitHub doesn’t create a tag on a draft release. So my compromise was to have this action print a warning on those triggers; but to do the upload when a full release is created. 

I will have to go look at your workflow, I don’t quite grok what is does.

**Comment by 1-alex98** [comment]
Well now it should be ok
