### ISSUE TITLE
Default Release Upload URL Fails

### ISSUE THREAD

**Issue by sommersoft** [csexton/release-action#6]
When #4 was merged, we started having the following failure with our release asset uploads:

```shell
> Run csexton/release-asset-action@master
Uploading file: bundles/adafruit-circuitpython-bundle-4.x-mpy-20200207.zip
Uploading file: bundles/adafruit-circuitpython-bundle-5.x-mpy-20200207.zip
Uploading file: bundles/adafruit-circuitpython-bundle-examples-20200207.zip
Uploading file: bundles/adafruit-circuitpython-bundle-py-20200207.zip
Uploading file: bundles/z-build_tools_version-1.4.1.ignore
##[error]Upload failed: Cookies must be enabled to use GitHub. undefined
Uploaded z-build_tools_version-1.4.1.ignore
##[error]Upload failed:  undefined
Uploaded adafruit-circuitpython-bundle-examples-20200207.zip
##[error]Upload failed:  undefined
Uploaded adafruit-circuitpython-bundle-4.x-mpy-20200207.zip
##[error]Upload failed:  undefined
Uploaded adafruit-circuitpython-bundle-py-20200207.zip
##[error]Upload failed:  undefined
Uploaded adafruit-circuitpython-bundle-5.x-mpy-20200207.zip
##[error]Node run failed with exit code 1
```

It took us a little while to figure out what would cause this, since the error messages didn't really point to the root cause. I finally settled on researching `Cookies must be enabled to use GitHub` and came across an old `octokit/rest.js` issue that pointed out the need to send requests to `https://api.github.com` vs `https://github.com`.

After debugging on a fork, I realized that this line was resulting in the default of a non-api URL:
[`url= core.getInput('release-url', {required: false}) || context.payload.release.html_url;`](https://github.com/csexton/release-asset-action/blob/master/main.js#L56)

By changing `|| context.payload.release.html_url` --> `|| context.payload.release.upload_url`, I had successful uploads.

I know you can now pass in the `release-url` variable, and I've worked that out using the available context expression in the workflow. However, we'd have over 200 repositories to update with that approach.

I'm just wanting to gauge interest, or reasoning, for having the default release upload URL be one that will fail.

I would happily submit a PR if a change is desired.

Also, thanks @csexton for this Action. Having glob pattern uploads is a life saver!

**Comment by csexton** [comment]
I wonder how it worked before, because am sure it did. Are you using the v2 tag?

A PR would be quite welcome. I’ll be on the lookout.

**Comment by sommersoft** [comment]
> I wonder how it worked before, because am sure it did.

Best I can tell, is that before it was hardcoded to use the `upload_url` when calling the upload function:
https://github.com/csexton/release-asset-action/blob/6a964e8a644f28832c3f9a46abc69dda52fc6d17/main.js#L31

I'll have a PR in shortly. I just wanted to make sure there wasn't some reason `html_url` was being used.

**Comment by 1-alex98** [comment]
Well #4 did not change anything concerning this is was html_url before #4 and also afterwards

**Comment by sommersoft** [comment]
Prior to #4, the URL was hardcoded to use `upload_url`:
```
async function upload(filePath, context, octokit) {
  ....
  try {
    let response  = await octokit.repos.uploadReleaseAsset({
      name: fileName,
      file: file,
-->   url: context.payload.release.upload_url,
      headers: {
        "content-length": file.length,
        "content-type": mimeType
      }
    });
```
4 changed it to use the passed in variable `url`, which was being set as `html_url` if no `release-url` was provided:
```
async function upload(filePath, context, octokit, url) {
  ....
  try {
    let response  = await octokit.repos.uploadReleaseAsset({
      name: fileName,
      file: file,
-->   url: url,
      headers: {
        "content-length": file.length,
        "content-type": mimeType
      }
    });

.....
url= core.getInput('release-url', {required: false}) || context.payload.release.html_url;
```
As I mentioned in my PR, I'm not entirely sure what `core.setOutput('url', ...)` is doing in `run()`. It is a confusing step for me in either version, as it doesn't seem to be actually used anywhere.

I also mentioned my lack of experience in JS, so if I'm completely misunderstanding how this codebase is working let me know.

**Comment by 1-alex98** [comment]
oh ok
